<?php

use Illuminate\Support\Facades\Auth;
use Livewire\Volt\Component;
use PragmaRX\Recovery\Recovery;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;

new class extends Component {
    public $secret;
    public $qrCodeUrl;
    public $showingQrCode = false;
    public $showingRecoveryCodes = false;
    public $recoveryCodes = [];
    public $code;
    public function mount()
    {
        $google2fa = app('pragmarx.google2fa');

        $user = Auth::user();
        $this->secret = $user->two_factor_secret;
        $this->recoveryCodes = $user->two_factor_recovery_codes;
        if (!$this->secret) {
            $this->secret = $google2fa->generateSecretKey();
            $this->recoveryCodes = (new Recovery())->toJson();
            //$this->qrCodeUrl = $google2fa->getQRCodeInline(config('app.name'), $user->email, $this->secret);
            $qrCodeText = $google2fa->getQRCodeUrl(
                config('app.name'),
                $user->email,
                $this->secret
            );

            $this->qrCodeUrl = $this->generateQrCodeDataUri($qrCodeText);
        }
    }

    private function generateQrCodeDataUri($text)
    {
        $qrCode = new QrCode($text);
        /* $qrCode->setSize(200);
        $qrCode->setMargin(10); */

        $writer = new PngWriter();
        $result = $writer->write($qrCode);

        return $result->getDataUri();
    }


    public function toggleQrCode()
    {
        $this->showingQrCode = !$this->showingQrCode;
    }

    public function toggleRecoveryCodes()
    {
        $this->showingRecoveryCodes = !$this->showingRecoveryCodes;
    }

    public function enableTwoFactor()
    {
        $google2fa = app('pragmarx.google2fa');
        $this->validate([
            'code' => [
                'required',
                'digits:6',
                function ($attribute, $value, $fail) use ($google2fa) {
                    if (!$google2fa->verifyKey($this->secret, $value)) {
                        $fail(__('The :attribute is invalid.'));
                    }
                },
            ],
        ]);

        $user = Auth::user();
        $user->two_factor_secret = $this->secret;
        $user->two_factor_recovery_codes = $this->recoveryCodes;
        $user->two_factor_confirmed_at = now();
        $user->save();

        $this->dispatch('done', success: 'Two Factor Authentication Enabled');
    }
    public function disableTwoFactor()
    {
        $user = Auth::user();
        $user->two_factor_secret = null;
        $user->two_factor_recovery_codes = null;
        $user->two_factor_confirmed_at = null;
        $user->save();
        $this->dispatch('done', success: 'Two Factor Authentication Disabled');
    }
}; ?>

<section class="w-full">
    @include('roles::partials.settings-heading')

    <x-roles::settings.layout :heading="__('Two Factor Authentication')" :subheading="__('Add additional security to your account using two factor authentication.')">
        @if (!Auth::user()->two_factor_secret)
            @if ($showingQrCode)
                <div class="mt-4 space-y-4">
                    <h3>Finish enabling two factor authentication.                    </h3>
                    <p class="text-zinc-700 dark:text-zinc-200">To finish enabling two factor authentication, scan the following QR code using your phone's authenticator application or enter the setup key and provide the generated OTP code.                    </p>
                    {{-- {!! $qrCodeUrl !!} --}}

                    <div class="flex justify-center">
                        <img src="{{ $qrCodeUrl }}" alt="QR Code" class="border rounded-lg">
                    </div>
                    <p>Setup key: {{ $secret }}</p>

                    <flux:input wire:model="code" type="text" label="Enter the Code Generated by the Authenticator App">
                    </flux:input>
                    <flux:error name="code"></flux:error>

                    <div class="grid grid-cols-2 gap-4">
                        <flux:button variant="primary" wire:click="enableTwoFactor" class="w-full">
                            {{ __('Enable Two Factor Authentication') }}
                        </flux:button>
                        <flux:button variant="primary" wire:click="toggleQrCode" class="w-full">
                            {{ __('Cancel') }}
                        </flux:button>

                    </div>
                </div>
            @else
                <div class="mt-4 space-y-4">
                    <p class="text-zinc-700 dark:text-zinc-200">You have not enabled two factor authentication.</p>
                    {{-- {!! $qrCodeUrl !!} --}}

                    <p>When two factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's Google Authenticator application.</p>

                    <flux:button variant="primary" wire:click="toggleQrCode" class="w-full">
                        {{ __('Enable') }}
                    </flux:button>
                    neutral
                    <x-mary-button label="You?" class="btn-neutral" />
                </div>
            @endif
        @else
            <div class="mt-4 space-y-4">
                <p class="text-zinc-700 dark:text-zinc-200">You have enabled two factor authentication.                </p>
                <p>When two factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's Google Authenticator application.                </p>
                <p class="text-zinc-700 dark:text-zinc-200">Store these recovery codes in a secure password manager. They can be used to recover access to your account if your two factor authentication device is lost.                </p>
                <flux:button variant="danger" wire:click="disableTwoFactor" class="w-full">
                    {{ __('Disable Two Factor Authentication') }}
                </flux:button>
                @if (!$showingRecoveryCodes)
                    <flux:button variant="primary" wire:click="toggleRecoveryCodes" class="w-full">
                        {{ __('Show Recovery Codes') }}
                    </flux:button>
                @else
                    <ul class="space-y-2 grid grid-cols-2 gap-2">
                        @foreach (json_decode($recoveryCodes) as $code)
                            <li>{{ $code }}</li>
                        @endforeach
                    </ul>

                    <flux:button variant="primary" class="w-full">
                        {{ __('Regenerate Recovery Codes') }}
                    </flux:button>

                    <flux:button variant="primary" class="w-full">
                        {{ __('Disable') }}
                    </flux:button>
                @endif
            </div>
        @endif
    </x-roles::settings.layout>
</section>
