<?php

/**
 * @OA\Schema(
 *   schema="SalesOrderRequest",
 *   type="object",
 *   required={"customer_id", "date", "line_items"},
 *   @OA\Property(property="customer_id", type="integer", example=4815000000044080),
 *   @OA\Property(property="salesorder_number", type="string", example="SO-00003"),
 *   @OA\Property(property="date", type="string", format="date", example="2015-05-28"),
 *   @OA\Property(property="shipment_date", type="string", format="date", example="2015-06-02"),
 *   @OA\Property(property="custom_fields", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="custom_field_id", type="integer", example=0),
 *     @OA\Property(property="index", type="integer", example=0),
 *     @OA\Property(property="label", type="string", example="string"),
 *     @OA\Property(property="value", type="string", example="string")
 *   )),
 *   @OA\Property(property="reference_number", type="string", example="REF-S-00003"),
 *   @OA\Property(property="location_id", type="string", example="460000000038080"),
 *   @OA\Property(property="line_items", type="array", @OA\Items(
 *     type="object",
 *     required={"item_id", "name", "quantity", "rate", "item_total"},
 *     @OA\Property(property="item_id", type="integer", example=4815000000044100),
 *     @OA\Property(property="name", type="string", example="Laptop-white/15inch/dell"),
 *     @OA\Property(property="description", type="string", example="Just a sample description."),
 *     @OA\Property(property="rate", type="number", format="float", example=122),
 *     @OA\Property(property="quantity", type="integer", example=2),
 *     @OA\Property(property="unit", type="string", example="qty"),
 *     @OA\Property(property="tax_id", type="integer", example=4815000000044043),
 *     @OA\Property(property="tds_tax_id", type="string", example="460000000017098"),
 *     @OA\Property(property="tax_name", type="string", example="Sales Tax"),
 *     @OA\Property(property="tax_type", type="string", example="tax"),
 *     @OA\Property(property="tax_percentage", type="number", format="float", example=12),
 *     @OA\Property(property="item_total", type="number", format="float", example=244),
 *     @OA\Property(property="location_id", type="string", example="460000000038080"),
 *     @OA\Property(property="hsn_or_sac", type="integer", example=80540),
 *     @OA\Property(property="sat_item_key_code", type="integer", example=71121206),
 *     @OA\Property(property="unitkey_code", type="string", example="E48")
 *   )),
 *   @OA\Property(property="notes", type="string", example="Sample Note"),
 *   @OA\Property(property="terms", type="string", example="Terms and Conditions"),
 *   @OA\Property(property="discount", type="string", example="20.00%"),
 *   @OA\Property(property="is_discount_before_tax", type="boolean", example=true),
 *   @OA\Property(property="discount_type", type="string", example="entity_level"),
 *   @OA\Property(property="shipping_charge", type="number", format="float", example=7),
 *   @OA\Property(property="delivery_method", type="string", example="FedEx"),
 *   @OA\Property(property="adjustment", type="number", format="float", example=0),
 *   @OA\Property(property="pricebook_id", type="integer", example=4815000000044054),
 *   @OA\Property(property="salesperson_id", type="integer", example=4815000000044762),
 *   @OA\Property(property="adjustment_description", type="string", example="Just an example description."),
 *   @OA\Property(property="is_inclusive_tax", type="boolean", example=false),
 *   @OA\Property(property="exchange_rate", type="number", format="float", example=1),
 *   @OA\Property(property="template_id", type="integer", example=4815000000017003),
 *   @OA\Property(property="documents", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="can_send_in_mail", type="boolean", example=true),
 *     @OA\Property(property="file_name", type="string", example="sample.pdf"),
 *     @OA\Property(property="file_type", type="string", example="pdf"),
 *     @OA\Property(property="file_size_formatted", type="string", example="116.8 KB"),
 *     @OA\Property(property="attachment_order", type="integer", example=1),
 *     @OA\Property(property="document_id", type="integer", example=16115000000096068),
 *     @OA\Property(property="file_size", type="integer", example=11957)
 *   )),
 *   @OA\Property(property="billing_address_id", type="integer", example=4815000000017005),
 *   @OA\Property(property="shipping_address_id", type="integer", example=4815000000017005),
 *   @OA\Property(property="place_of_supply", type="string", example="TN"),
 *   @OA\Property(property="gst_treatment", type="string", example="business_gst"),
 *   @OA\Property(property="gst_no", type="string", example="22AAAAA0000A1Z5")
 * )
 */

/**
 * @OA\Schema(
 *   schema="SalesOrderUpdateRequest",
 *   type="object",
 *   @OA\Property(property="salesorder_number", type="string", example="SO-00003"),
 *   @OA\Property(property="date", type="string", format="date", example="2015-05-28"),
 *   @OA\Property(property="shipment_date", type="string", format="date", example="2015-06-02"),
 *   @OA\Property(property="custom_fields", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="custom_field_id", type="integer", example=0),
 *     @OA\Property(property="index", type="integer", example=0),
 *     @OA\Property(property="label", type="string", example="string"),
 *     @OA\Property(property="value", type="string", example="string")
 *   )),
 *   @OA\Property(property="reference_number", type="string", example="REF-S-00003"),
 *   @OA\Property(property="customer_id", type="integer", example=4815000000044080),
 *   @OA\Property(property="contact_persons", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="contact_person_id", type="integer", example=4815000000044080)
 *   )),
 *   @OA\Property(property="discount", type="string", example="20.00%"),
 *   @OA\Property(property="is_discount_before_tax", type="boolean", example=true),
 *   @OA\Property(property="discount_type", type="string", example="entity_level"),
 *   @OA\Property(property="delivery_method", type="string", example="FedEx"),
 *   @OA\Property(property="shipping_charge", type="number", format="float", example=7),
 *   @OA\Property(property="adjustment", type="number", format="float", example=0),
 *   @OA\Property(property="adjustment_description", type="string", example="Just an example description."),
 *   @OA\Property(property="pricebook_id", type="integer", example=4815000000044054),
 *   @OA\Property(property="notes", type="string", example="Sample Note"),
 *   @OA\Property(property="salesperson_name", type="string", example="Lara"),
 *   @OA\Property(property="terms", type="string", example="Terms and Conditions"),
 *   @OA\Property(property="exchange_rate", type="number", format="float", example=1),
 *   @OA\Property(property="line_items", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="line_item_id", type="integer", example=4815000000044897),
 *     @OA\Property(property="item_id", type="integer", example=4815000000044100),
 *     @OA\Property(property="name", type="string", example="Laptop-white/15inch/dell"),
 *     @OA\Property(property="description", type="string", example="Just a sample description."),
 *     @OA\Property(property="rate", type="number", format="float", example=122),
 *     @OA\Property(property="quantity", type="integer", example=2),
 *     @OA\Property(property="unit", type="string", example="qty"),
 *     @OA\Property(property="tax_id", type="integer", example=4815000000044043),
 *     @OA\Property(property="tds_tax_id", type="string", example="460000000017098"),
 *     @OA\Property(property="tax_name", type="string", example="Sales Tax"),
 *     @OA\Property(property="tax_type", type="string", example="tax"),
 *     @OA\Property(property="tax_percentage", type="number", format="float", example=12),
 *     @OA\Property(property="item_total", type="number", format="float", example=244),
 *     @OA\Property(property="location_id", type="string", example="460000000038080"),
 *     @OA\Property(property="hsn_or_sac", type="integer", example=80540),
 *     @OA\Property(property="sat_item_key_code", type="integer", example=71121206),
 *     @OA\Property(property="unitkey_code", type="string", example="E48")
 *   )),
 *   @OA\Property(property="location_id", type="string", example="460000000038080"),
 *   @OA\Property(property="billing_address_id", type="integer", example=4815000000017005),
 *   @OA\Property(property="shipping_address_id", type="integer", example=4815000000017005),
 *   @OA\Property(property="place_of_supply", type="string", example="TN"),
 *   @OA\Property(property="gst_treatment", type="string", example="business_gst"),
 *   @OA\Property(property="gst_no", type="string", example="22AAAAA0000A1Z5")
 * )
 */

/**
 * @OA\Schema(
 *   schema="SalesOrderResponse",
 *   type="object",
 *   @OA\Property(property="salesorder_id", type="integer", example=4815000000044895),
 *   @OA\Property(property="salesorder_number", type="string", example="SO-00003"),
 *   @OA\Property(property="date", type="string", format="date", example="2015-05-28"),
 *   @OA\Property(property="status", type="string", example="fulfilled"),
 *   @OA\Property(property="shipment_date", type="string", format="date", example="2015-06-02"),
 *   @OA\Property(property="reference_number", type="string", example="REF-S-00003"),
 *   @OA\Property(property="customer_id", type="integer", example=4815000000044080),
 *   @OA\Property(property="customer_name", type="string", example="Molly"),
 *   @OA\Property(property="contact_persons", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="contact_person_id", type="integer", example=4815000000044080)
 *   )),
 *   @OA\Property(property="currency_id", type="integer", example=4815000000000097),
 *   @OA\Property(property="currency_code", type="string", example="USD"),
 *   @OA\Property(property="currency_symbol", type="string", example="$"),
 *   @OA\Property(property="exchange_rate", type="number", format="float", example=1),
 *   @OA\Property(property="discount_amount", type="number", format="float", example=0),
 *   @OA\Property(property="discount", type="string", example="20.00%"),
 *   @OA\Property(property="is_discount_before_tax", type="boolean", example=true),
 *   @OA\Property(property="discount_type", type="string", example="entity_level"),
 *   @OA\Property(property="estimate_id", type="integer", example=4815000000045091),
 *   @OA\Property(property="delivery_method", type="string", example="FedEx"),
 *   @OA\Property(property="delivery_method_id", type="integer", example=4815000000044822),
 *   @OA\Property(property="line_items", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="item_id", type="integer", example=4815000000044100),
 *     @OA\Property(property="line_item_id", type="integer", example=4815000000044897),
 *     @OA\Property(property="name", type="string", example="Laptop-white/15inch/dell"),
 *     @OA\Property(property="description", type="string", example="Just a sample description."),
 *     @OA\Property(property="item_order", type="integer", example=0),
 *     @OA\Property(property="bcy_rate", type="number", format="float", example=122),
 *     @OA\Property(property="rate", type="number", format="float", example=122),
 *     @OA\Property(property="quantity", type="integer", example=2),
 *     @OA\Property(property="quantity_invoiced", type="integer", example=2),
 *     @OA\Property(property="quantity_packed", type="integer", example=2),
 *     @OA\Property(property="quantity_shipped", type="integer", example=2),
 *     @OA\Property(property="unit", type="string", example="qty"),
 *     @OA\Property(property="tax_id", type="integer", example=4815000000044043),
 *     @OA\Property(property="tds_tax_id", type="string", example="460000000017098"),
 *     @OA\Property(property="tax_name", type="string", example="Sales Tax"),
 *     @OA\Property(property="tax_type", type="string", example="tax"),
 *     @OA\Property(property="tax_percentage", type="number", format="float", example=12),
 *     @OA\Property(property="item_total", type="number", format="float", example=244),
 *     @OA\Property(property="is_invoiced", type="boolean", example=true),
 *     @OA\Property(property="image_id", type="integer", example=2077500000000002000),
 *     @OA\Property(property="image_name", type="string", example="dell.jpg"),
 *     @OA\Property(property="image_type", type="string", example="jpg"),
 *     @OA\Property(property="location_id", type="string", example="460000000038080"),
 *     @OA\Property(property="location_name", type="string", example="string"),
 *     @OA\Property(property="hsn_or_sac", type="integer", example=80540),
 *     @OA\Property(property="sat_item_key_code", type="integer", example=71121206),
 *     @OA\Property(property="unitkey_code", type="string", example="E48")
 *   )),
 *   @OA\Property(property="location_id", type="string", example="460000000038080"),
 *   @OA\Property(property="location_name", type="string", example="string"),
 *   @OA\Property(property="shipping_charge", type="number", format="float", example=7),
 *   @OA\Property(property="adjustment", type="number", format="float", example=0),
 *   @OA\Property(property="adjustment_description", type="string", example="Just an example description."),
 *   @OA\Property(property="sub_total", type="number", format="float", example=244),
 *   @OA\Property(property="tax_total", type="number", format="float", example=29),
 *   @OA\Property(property="total", type="number", format="float", example=350),
 *   @OA\Property(property="taxes", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="tax_name", type="string", example="Sales Tax"),
 *     @OA\Property(property="tax_amount", type="number", format="float", example=29.28)
 *   )),
 *   @OA\Property(property="price_precision", type="integer", example=2),
 *   @OA\Property(property="pricebook_id", type="integer", example=4815000000044054),
 *   @OA\Property(property="shipping_address", type="object",
 *     @OA\Property(property="address", type="string", example="No:432,Bayside,Queens"),
 *     @OA\Property(property="city", type="string", example="New York City"),
 *     @OA\Property(property="state", type="string", example="New York"),
 *     @OA\Property(property="zip", type="integer", example=11364),
 *     @OA\Property(property="country", type="string", example="U.S.A"),
 *     @OA\Property(property="fax", type="string", example="424-524242")
 *   ),
 *   @OA\Property(property="billing_address", type="object",
 *     @OA\Property(property="address", type="string", example="No:432,Bayside,Queens"),
 *     @OA\Property(property="city", type="string", example="New York City"),
 *     @OA\Property(property="state", type="string", example="New York"),
 *     @OA\Property(property="zip", type="integer", example=11364),
 *     @OA\Property(property="country", type="string", example="U.S.A"),
 *     @OA\Property(property="fax", type="string", example="424-524242")
 *   ),
 *   @OA\Property(property="notes", type="string", example="Sample Note"),
 *   @OA\Property(property="terms", type="string", example="Terms and Conditions"),
 *   @OA\Property(property="template_id", type="integer", example=4815000000017003),
 *   @OA\Property(property="template_name", type="string", example="Standard"),
 *   @OA\Property(property="template_type", type="string", example="standard"),
 *   @OA\Property(property="created_time", type="string", format="date-time", example="2015-05-28T00:00:00.000Z"),
 *   @OA\Property(property="last_modified_time", type="string", format="date-time", example="2015-05-28T00:00:00.000Z"),
 *   @OA\Property(property="salesperson_id", type="integer", example=4815000000044762),
 *   @OA\Property(property="salesperson_name", type="string", example="Lara"),
 *   @OA\Property(property="documents", type="array", @OA\Items(
 *     type="object",
 *     @OA\Property(property="can_send_in_mail", type="boolean", example=true),
 *     @OA\Property(property="file_name", type="string", example="sample.pdf"),
 *     @OA\Property(property="file_type", type="string", example="pdf"),
 *     @OA\Property(property="file_size_formatted", type="string", example="116.8 KB"),
 *     @OA\Property(property="attachment_order", type="integer", example=1),
 *     @OA\Property(property="document_id", type="integer", example=16115000000096068),
 *     @OA\Property(property="file_size", type="integer", example=11957)
 *   )),
 *   @OA\Property(property="is_pre_gst", type="boolean", example=false),
 *   @OA\Property(property="gst_no", type="string", example="22AAAAA0000A1Z5"),
 *   @OA\Property(property="gst_treatment", type="string", example="business_gst"),
 *   @OA\Property(property="place_of_supply", type="string", example="TN")
 * )
 */
