<?php

use Livewire\Attributes\Layout;
use Livewire\Volt\Component;

new #[Layout('roles::components.layouts.auth')]  class extends Component {
    public $code;

    protected $rules = [
        'code' => 'required|digits:6',
    ];
    protected $messages = [
        'code.required' => 'The :attribute is required.',
        'code.digits' => 'The :attribute must be 6 digits.',
    ];
    public function verify()
    {
        $this->validate();

        $google2fa = app('pragmarx.google2fa');
        $user = Auth::user();

        if ($google2fa->verifyKey($user->two_factor_secret, $this->code)) {
            $user->two_factor_confirmed_at = now();
            $user->save();
            $this->redirectIntended(default: route('dashboard', absolute: false), navigate: true);
        } else {
            $this->addError('code', 'The code is invalid.');
            return;
        }
    }
}; ?>

<div class="flex flex-col gap-6">
    <x-auth-header :title="__('Two Factor Verification')" :description="__('Verify using the code generated by your Authenticator App')" />

    <!-- Session Status -->
    <x-auth-session-status class="text-center" :status="session('status')" />

    <form wire:submit="verify" class="flex flex-col gap-6">
        <!-- Email Address -->
        <flux:input
            wire:model="code"
            :label="__('Two Factor Authentication Code')"
            type="text"
            placeholder="******" />


        <div class="flex items-center justify-end">
            <flux:button variant="primary" type="submit" class="w-full">{{ __('Verify') }}</flux:button>
        </div>
    </form>
    <div class="flex items-center justify-center">
        <form method="POST" action="{{ route('logout') }}" class="w-full">
            @csrf
            <flux:button type="submit" icon="arrow-right-start-on-rectangle" variant="danger" class="w-full">
                {{ __('Log Out') }}
            </flux:button>
        </form>
    </div>

</div>
